# Generated by Django 4.1.7 on 2023-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twineapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
