# Generated by Django 4.1.7 on 2023-03-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twineapi', '0004_alter_ticket_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketflag',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_flags', to='twineapi.flag'),
        ),
    ]
